version: "3.8"
services:
  front:
    build: ./
    container_name: node
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true